apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanner
            image: vrusi/pannet-hiring-exercise
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure