---
- name: pannet
  hosts: linux
  tasks:
    - name: install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: install requirements
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        [
          "apt-transport-https",
          "ca-certificates",
          "curl",
          "software-properties-common",
          "python3-pip",
          "virtualenv",
          "python3-setuptools",
        ]

    - name: add gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: install python docker module
      pip:
       name: docker

    - name: pull image
      docker_image:
       name: "{{ container_image }}"
       source: pull
       
    - name: create containers
      docker_container:
        name: "{{ container_name }}{{ item }}"
        image: "{{ container_image }}"
        command: "{{ container_command }}"
        state: present
        log_driver: syslog
      with_sequence: count={{ containers }}
